-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" STRING NOT NULL,
    "password" STRING NOT NULL,
    "email" STRING NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserTwitchTokenData" (
    "userId" INT4 NOT NULL,
    "accessToken" STRING NOT NULL,
    "expiresIn" INT4 NOT NULL DEFAULT NULL,
    "obtainmentTimestamp" INT4 NOT NULL,
    "refreshToken" STRING,
    "scope" STRING[]
);

-- CreateTable
CREATE TABLE "TtsConfig" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,

    CONSTRAINT "TtsConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "UserTwitchTokenData_userId_key" ON "UserTwitchTokenData"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "TtsConfig_userId_key" ON "TtsConfig"("userId");

-- AddForeignKey
ALTER TABLE "UserTwitchTokenData" ADD CONSTRAINT "UserTwitchTokenData_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TtsConfig" ADD CONSTRAINT "TtsConfig_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
